
name: php laravel WorkFlow

on:
  push:
    branches:
      - main
      

jobs:
  app-tests:
    runs-on: ubuntu-latest
    steps:
      - name: check the repo
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - run: php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
             && php composer-setup.php \
             && php -r "unlink('composer-setup.php');" \
             && php composer.phar install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader \
      -  run: npm install
      - name: Generate key
        run: php artisan key:generate
      - name: Execute phpunit test
        run: ./vendor/bin/phpunit
  deploy-production:
    name: Deploy Project to PRODUCTION Server
    runs-on: ubuntu-latest
    needs: [app-tests]
    if: github.ref == 'refs/heads/master'
    steps:
      - name: code checking
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extension-csv: mbstring, bcmath
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Setup Deployer
        uses: atymic/deployer-php-action@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-known-hosts: ${{ secrets.SSH_KNOWN_HOSTS }}
      - name: Deploy to Prod
        uses: appleboy/ssh-action@master 
        with:
          username: ${{ secrets.USER }}
          host: ${{ secrets.HOST }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
          script: "cd /var/www/project &&  sudo sh deploy.sh"
  
